languages:
- python


- name: python
  production:
    exclude:
      - /algocoin/tests/.*
  test:
    include:
      - /algocoin/tests/.*

exclude:
- /docs/.*
- .*/setup\.py
- /algocoin/order_entry.py
- /scripts/.*
- /algocoin/logging\.py
- /algocoin/define\.py
- /algocoin/custom\_strategies\.py
- /custom_strategies/.*
- /algocoin/strategies/.*
