languages:
- python


- name: python
  production:
    exclude:
      - /tests/.*
  test:
    include:
      - /tests/.*

exclude:
- /docs/.*
- .*/setup\.py
- /algocoin/lib/oe/.*
- /algocoin/lib/oe/poloniex/.*
- /scripts/.*
- /algocoin/lib/logging\.py
- /algocoin/lib/define\.py